#!/usr/bin/env python3
"""Conservative, dependency-free code-rot candidate scanner."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SOURCE_EXTENSIONS = {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".py"}
TEXT_EXTENSIONS = SOURCE_EXTENSIONS | {".json", ".yaml", ".yml", ".toml", ".md", ".html", ".css", ".scss"}
EXCLUDED_DIRS = {
    ".git", ".hg", ".svn", ".next", ".nuxt", ".svelte-kit", ".venv", "venv",
    "node_modules", "vendor", "dist", "build", "coverage", "target", "out",
    "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", "outputs",
}
ROOT_NAMES = {
    "index.js", "index.jsx", "index.ts", "index.tsx", "main.js", "main.jsx", "main.ts",
    "main.tsx", "app.js", "app.jsx", "app.ts", "app.tsx", "server.js", "server.ts",
    "cli.js", "cli.ts", "manage.py", "wsgi.py", "asgi.py", "__main__.py", "conftest.py",
}
CONVENTION_PARTS = {
    "pages", "routes", "migrations", "commands", "management", "workers", "jobs",
    "scripts", "plugins", "stories", "fixtures", "seeds",
}
GENERATED_MARKERS = ("generated", "autogenerated", "auto-generated", "do not edit")


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def safe_text(path: Path, limit: int = 2_000_000) -> str:
    try:
        if path.stat().st_size > limit:
            return ""
        return path.read_text(encoding="utf-8", errors="ignore")
    except (OSError, UnicodeError):
        return ""


def relative(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def walk_files(root: Path, extensions: set[str]) -> list[Path]:
    files: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in extensions:
            continue
        try:
            parts = path.relative_to(root).parts[:-1]
        except ValueError:
            continue
        if any(part in EXCLUDED_DIRS or part.startswith(".git") for part in parts):
            continue
        files.append(path)
    return sorted(files)


def line_count(text: str) -> int:
    return len(text.splitlines()) if text else 0


def load_package_roots(root: Path) -> tuple[set[str], dict[str, Any]]:
    package_path = root / "package.json"
    if not package_path.exists():
        return set(), {}
    try:
        package = json.loads(package_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return set(), {}

    roots: set[str] = set()

    def collect(value: Any) -> None:
        if isinstance(value, str) and value.startswith("."):
            cleaned = value.split("?")[0].lstrip("./")
            if cleaned:
                roots.add(cleaned)
        elif isinstance(value, dict):
            for child in value.values():
                collect(child)
        elif isinstance(value, list):
            for child in value:
                collect(child)

    for key in ("main", "module", "browser", "bin", "exports"):
        collect(package.get(key))
    for script in (package.get("scripts") or {}).values():
        if isinstance(script, str):
            for match in re.findall(r"(?:^|\s)([\w./-]+\.(?:[cm]?[jt]sx?|py))(?:\s|$)", script):
                roots.add(match.lstrip("./"))
    return roots, package


def is_convention_root(rel: str, text: str, package_roots: set[str]) -> bool:
    path = Path(rel)
    if rel in package_roots or path.name in ROOT_NAMES:
        return True
    if path.name.startswith(("next.config.", "vite.config.", "webpack.config.", "rollup.config.")):
        return True
    if any(part in CONVENTION_PARTS for part in path.parts[:-1]):
        return True
    if path.name in {"page.tsx", "page.ts", "layout.tsx", "layout.ts", "route.ts", "route.js"}:
        return True
    if path.name.startswith("test_") or ".test." in path.name or ".spec." in path.name:
        return True
    if path.name == "__init__.py":
        return True
    head = text[:500].lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def js_specifiers(text: str) -> list[str]:
    patterns = [
        r"\b(?:import|export)\s+(?:[^;\n]*?\s+from\s+)?['\"]([^'\"]+)['\"]",
        r"\brequire\s*\(\s*['\"]([^'\"]+)['\"]\s*\)",
        r"\bimport\s*\(\s*['\"]([^'\"]+)['\"]\s*\)",
    ]
    found: list[str] = []
    for pattern in patterns:
        found.extend(re.findall(pattern, text))
    return found


def python_specifiers(text: str) -> list[str]:
    found = re.findall(r"^\s*from\s+([.\w]+)\s+import\s+", text, flags=re.MULTILINE)
    found.extend(re.findall(r"^\s*import\s+([\w.]+)", text, flags=re.MULTILINE))
    return found


def resolve_js(source: Path, specifier: str, root: Path, source_set: set[Path]) -> Path | None:
    if not specifier.startswith("."):
        return None
    base = (source.parent / specifier).resolve()
    options = [base]
    if not base.suffix:
        options.extend(base.with_suffix(ext) for ext in SOURCE_EXTENSIONS if ext != ".py")
        options.extend(base / f"index{ext}" for ext in SOURCE_EXTENSIONS if ext != ".py")
    for option in options:
        if option in source_set and root in option.parents:
            return option
    return None


def resolve_python(source: Path, specifier: str, root: Path, source_set: set[Path]) -> Path | None:
    level = len(specifier) - len(specifier.lstrip("."))
    module = specifier.lstrip(".")
    base = source.parent
    for _ in range(max(0, level - 1)):
        base = base.parent
    if level == 0:
        base = root
    module_path = Path(*module.split(".")) if module else Path()
    for option in ((base / module_path).with_suffix(".py"), base / module_path / "__init__.py"):
        option = option.resolve()
        if option in source_set and (option == root or root in option.parents):
            return option
    return None


def normalize_duplicate_text(text: str) -> str:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    return "\n".join(lines)


def candidate(category: str, subject: str, path: str | None, confidence: str, risk: str,
              proof_eligible: bool, loc: int, size: int, evidence: list[str], caveats: list[str],
              line: int | None = None) -> dict[str, Any]:
    result: dict[str, Any] = {
        "category": category,
        "subject": subject,
        "path": path,
        "confidence": confidence,
        "initial_status": "REVIEW",
        "risk": risk,
        "proof_eligible": proof_eligible,
        "loc": loc,
        "bytes": size,
        "evidence": evidence,
        "caveats": caveats,
    }
    if line is not None:
        result["line"] = line
    return result


def analyze(root: Path) -> dict[str, Any]:
    root = root.resolve()
    if not root.is_dir():
        raise ValueError(f"Project root is not a directory: {root}")

    source_files = walk_files(root, SOURCE_EXTENSIONS)
    text_files = walk_files(root, TEXT_EXTENSIONS)
    source_set = {path.resolve() for path in source_files}
    texts = {path: safe_text(path) for path in text_files}
    package_roots, package = load_package_roots(root)
    inbound: dict[Path, set[Path]] = defaultdict(set)
    imported_packages: set[str] = set()
    for source in source_files:
        text = texts.get(source, "")
        if source.suffix.lower() in {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}:
            for specifier in js_specifiers(text):
                target = resolve_js(source, specifier, root, source_set)
                if target:
                    inbound[target].add(source)
                elif not specifier.startswith((".", "/", "#")):
                    package_name = "/".join(specifier.split("/")[:2]) if specifier.startswith("@") else specifier.split("/")[0]
                    imported_packages.add(package_name)
        elif source.suffix.lower() == ".py":
            for specifier in python_specifiers(text):
                target = resolve_python(source, specifier, root, source_set)
                if target:
                    inbound[target].add(source)

    all_repository_text = "\n".join(texts.values())
    candidates: list[dict[str, Any]] = []

    for path in source_files:
        rel = relative(path, root)
        text = texts.get(path, "")
        if is_convention_root(rel, text, package_roots) or inbound.get(path.resolve()):
            continue
        tokens = {path.name, path.stem, rel, rel.rsplit(".", 1)[0]}
        own_text = text
        outside_text = all_repository_text.replace(own_text, "", 1)
        mentions = [token for token in tokens if len(token) >= 4 and token in outside_text]
        convention_sensitive = any(part in {"app", "src"} and path.name.startswith(("route.", "page.", "layout.")) for part in path.parts)
        confidence = "medium" if mentions or convention_sensitive else "high"
        risk = "medium" if mentions or convention_sensitive else "low"
        evidence = ["No resolved static inbound import was found.", "The file is not a detected package or conventional entry point."]
        caveats = ["Dynamic loading, reflection, external consumers, or incomplete framework detection can hide reachability."]
        if mentions:
            evidence.append(f"Repository text contains possible string/name references: {', '.join(sorted(mentions)[:4])}.")
            caveats.append("Possible string reachability prevents high-confidence deletion.")
        candidates.append(candidate(
            "orphan-file", rel, rel, confidence, risk, confidence == "high" and risk == "low",
            line_count(text), path.stat().st_size, evidence, caveats,
        ))

    duplicate_groups: dict[str, list[Path]] = defaultdict(list)
    for path in source_files:
        text = texts.get(path, "")
        normalized = normalize_duplicate_text(text)
        if line_count(normalized) >= 4 and len(normalized) >= 80:
            duplicate_groups[hashlib.sha256(normalized.encode()).hexdigest()].append(path)
    for paths in duplicate_groups.values():
        if len(paths) < 2:
            continue
        rels = [relative(path, root) for path in sorted(paths)]
        for duplicate in rels[1:]:
            path = root / duplicate
            text = texts.get(path, "")
            candidates.append(candidate(
                "duplicate-file", f"{duplicate} duplicates {rels[0]}", duplicate, "high", "medium", False,
                line_count(text), path.stat().st_size,
                [f"Normalized content matches {rels[0]} exactly."],
                ["Duplication is not proof that either implementation is unreachable.", "Callers may depend on separate module boundaries."],
            ))

    dependencies: dict[str, str] = {}
    for section in ("dependencies", "devDependencies", "optionalDependencies"):
        for name in (package.get(section) or {}):
            dependencies[name] = section
    script_text = json.dumps(package.get("scripts") or {})
    package_texts = script_text + "\n" + "\n".join(
        text for path, text in texts.items()
        if path.name not in {"package.json", "package-lock.json", "npm-shrinkwrap.json"}
    )
    for name, section in sorted(dependencies.items()):
        name_pattern = re.compile(rf"(?<![\w@/-]){re.escape(name)}(?![\w@-])")
        if name in imported_packages or name_pattern.search(package_texts):
            continue
        candidates.append(candidate(
            "unused-dependency", f"{name} ({section})", "package.json", "medium", "medium", False, 0, 0,
            ["No static JavaScript/TypeScript import or repository text reference was found."],
            ["CLIs, loaders, presets, peer relationships, scripts, and runtime configuration may use this package.", "Manifest and lockfile changes require explicit approval."],
        ))

    export_pattern = re.compile(r"\bexport\s+(?:default\s+)?(?:async\s+)?(?:function|class|const|let|var|type|interface|enum)\s+([A-Za-z_$][\w$]*)")
    for path in source_files:
        if path.suffix.lower() not in {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}:
            continue
        rel = relative(path, root)
        text = texts.get(path, "")
        for match in export_pattern.finditer(text):
            symbol = match.group(1)
            if len(symbol) < 4:
                continue
            outside = all_repository_text.replace(text, "", 1)
            if re.search(rf"\b{re.escape(symbol)}\b", outside):
                continue
            candidates.append(candidate(
                "unused-export", f"{symbol} from {rel}", rel, "medium", "medium", False, 0, 0,
                ["No reference to the exported symbol was found outside its defining file."],
                ["Public APIs, re-export patterns, generated declarations, templates, or external consumers may use it."],
                text[:match.start()].count("\n") + 1,
            ))

    comment_pattern = re.compile(r"(?m)(?:^\s*//.*(?:[;{}()]|\b(?:if|for|return|const|let|var|function)\b).*$\n?){4,}")
    for path in source_files:
        if path.suffix.lower() not in {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}:
            continue
        text = texts.get(path, "")
        for match in comment_pattern.finditer(text):
            block = match.group(0)
            rel = relative(path, root)
            candidates.append(candidate(
                "commented-code", f"Comment block in {rel}", rel, "low", "medium", False,
                line_count(block), len(block.encode()),
                ["A block of four or more code-like line comments was found."],
                ["The block may be documentation, an example, a protocol, or an intentional workaround."],
                text[:match.start()].count("\n") + 1,
            ))

    category_order = {"orphan-file": 0, "unused-dependency": 1, "unused-export": 2, "duplicate-file": 3, "commented-code": 4}
    candidates.sort(key=lambda item: (category_order.get(item["category"], 99), item.get("path") or "", item["subject"]))
    for index, item in enumerate(candidates, start=1):
        item["id"] = f"CRT-{index:03d}"

    potential = [item for item in candidates if item["category"] in {"orphan-file", "duplicate-file", "commented-code"}]
    potential_by_path: dict[str, dict[str, Any]] = {}
    for item in potential:
        key = item.get("path") or item["id"]
        current = potential_by_path.get(key)
        if current is None or item["loc"] > current["loc"]:
            potential_by_path[key] = item
    return {
        "schema_version": "1.0",
        "project_root": str(root),
        "generated_at": utc_now(),
        "scope": {
            "source_extensions": sorted(SOURCE_EXTENSIONS),
            "excluded_directories": sorted(EXCLUDED_DIRS),
            "source_files": len(source_files),
            "source_loc": sum(line_count(texts.get(path, "")) for path in source_files),
            "source_bytes": sum(path.stat().st_size for path in source_files),
        },
        "summary": {
            "candidates": len(candidates),
            "proof_eligible": sum(1 for item in candidates if item["proof_eligible"]),
            "potential_removable_loc": sum(item["loc"] for item in potential_by_path.values()),
            "potential_removable_bytes": sum(item["bytes"] for item in potential_by_path.values()),
            "by_category": {category: sum(1 for item in candidates if item["category"] == category) for category in category_order},
        },
        "candidates": candidates,
        "limitations": [
            "Static analysis cannot prove absence of dynamic, reflective, operational, platform-specific, or external use.",
            "JavaScript/TypeScript and Python import resolution is intentionally conservative and does not implement every alias or framework convention.",
            "Unused dependencies and exports are leads only until project-native tooling and focused proof support removal.",
            "No project code, package command, or dependency was executed by this scanner.",
        ],
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", type=Path, help="Project root to inspect")
    parser.add_argument("output", type=Path, help="Analysis JSON path")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    result = analyze(args.project)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(f"Analyzed {result['scope']['source_files']} source files.")
    print(f"Found {result['summary']['candidates']} candidates; {result['summary']['proof_eligible']} proof-eligible.")
    print(f"Evidence: {args.output.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
