"""JavaScript and TypeScript resolution, ecosystem, and Knip evidence."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from security import run_approved_tool


JS_EXTENSIONS = {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".mts", ".cts"}
ROOT_NAMES = {
    "index.js", "index.jsx", "index.ts", "index.tsx", "main.js", "main.jsx",
    "main.ts", "main.tsx", "app.js", "app.ts", "server.js", "server.ts",
    "cli.js", "cli.ts", "middleware.js", "middleware.ts",
}
CONVENTION_DIRECTORIES = {
    "migrations", "plugins", "scripts", "workers", "jobs", "commands", "seeds",
    "fixtures", "stories", "__tests__",
}
GENERATED_MARKERS = ("generated", "autogenerated", "auto-generated", "do not edit")


def load_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def load_jsonc(path: Path) -> dict[str, Any]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"(^|\s)//.*$", r"\1", text, flags=re.MULTILINE)
    text = re.sub(r",\s*([}\]])", r"\1", text)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return {}


def js_specifiers(text: str) -> list[str]:
    patterns = (
        r"\b(?:import|export)\s+(?:[^;\n]*?\s+from\s+)?['\"]([^'\"]+)['\"]",
        r"\brequire\s*\(\s*['\"]([^'\"]+)['\"]\s*\)",
        r"\bimport\s*\(\s*['\"]([^'\"]+)['\"]\s*\)",
    )
    return [match for pattern in patterns for match in re.findall(pattern, text)]


def has_nonliteral_dynamic_import(text: str) -> bool:
    return bool(re.search(r"\b(?:import|require)\s*\(\s*(?!['\"])", text))


def _source_options(base: Path) -> list[Path]:
    options = [base]
    if not base.suffix:
        options.extend(base.with_suffix(extension) for extension in sorted(JS_EXTENSIONS))
        options.extend(base / f"index{extension}" for extension in sorted(JS_EXTENSIONS))
    return options


def _first_source(options: list[Path], root: Path, source_set: set[Path]) -> Path | None:
    for option in options:
        try:
            resolved = option.resolve()
        except OSError:
            continue
        if resolved in source_set and (resolved == root or root in resolved.parents):
            return resolved
    return None


def resolve_specifier(source: Path, specifier: str, context: dict[str, Any]) -> Path | None:
    root: Path = context["root"]
    source_set: set[Path] = context["source_set"]
    if specifier.startswith("."):
        return _first_source(_source_options(source.parent / specifier), root, source_set)

    for alias, targets in context["path_mappings"].items():
        if "*" in alias:
            prefix, suffix = alias.split("*", 1)
            if not specifier.startswith(prefix) or (suffix and not specifier.endswith(suffix)):
                continue
            middle = specifier[len(prefix):len(specifier) - len(suffix) if suffix else None]
        elif specifier == alias:
            middle = ""
        else:
            continue
        for target in targets:
            candidate = Path(str(target).replace("*", middle))
            found = _first_source(_source_options(candidate), root, source_set)
            if found:
                return found

    for base_url in context["base_urls"]:
        found = _first_source(_source_options(base_url / specifier), root, source_set)
        if found:
            return found
    return None


def _collect_values(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        return [item for child in value.values() for item in _collect_values(child)]
    if isinstance(value, list):
        return [item for child in value for item in _collect_values(child)]
    return []


def build_context(root: Path, source_set: set[Path]) -> dict[str, Any]:
    manifests = sorted(
        path for path in root.rglob("package.json")
        if path.is_file() and not path.is_symlink() and "node_modules" not in path.parts
    )
    packages: list[dict[str, Any]] = []
    entry_files: set[Path] = set()
    has_workspaces = False
    dependency_names: set[str] = set()
    for manifest_path in manifests:
        manifest = load_json(manifest_path)
        if not manifest:
            continue
        has_workspaces = has_workspaces or bool(manifest.get("workspaces"))
        for section in ("dependencies", "devDependencies", "optionalDependencies", "peerDependencies"):
            dependency_names.update((manifest.get(section) or {}).keys())
        for field in ("main", "module", "browser", "bin", "exports"):
            for value in _collect_values(manifest.get(field)):
                if not value.startswith("."):
                    continue
                found = _first_source(_source_options(manifest_path.parent / value.split("?")[0]), root, source_set)
                if found:
                    entry_files.add(found)
        script_text = json.dumps(manifest.get("scripts") or {})
        for match in re.findall(r"([\w./-]+\.(?:[cm]?[jt]sx?))", script_text):
            found = _first_source(_source_options(manifest_path.parent / match), root, source_set)
            if found:
                entry_files.add(found)
        packages.append({"path": manifest_path, "data": manifest})

    path_mappings: dict[str, list[Path]] = {}
    base_urls: list[Path] = []
    project_references: list[str] = []
    for config_path in sorted(root.rglob("tsconfig*.json")):
        if "node_modules" in config_path.parts or config_path.is_symlink():
            continue
        config = load_jsonc(config_path)
        compiler = config.get("compilerOptions") or {}
        base = (config_path.parent / compiler.get("baseUrl", ".")).resolve()
        base_urls.append(base)
        for alias, targets in (compiler.get("paths") or {}).items():
            path_mappings.setdefault(alias, []).extend((base / target) for target in targets if isinstance(target, str))
        for reference in config.get("references") or []:
            if isinstance(reference, dict) and isinstance(reference.get("path"), str):
                project_references.append((config_path.parent / reference["path"]).resolve().relative_to(root).as_posix())

    package_manager = "npm"
    if (root / "pnpm-lock.yaml").exists() or (root / "pnpm-workspace.yaml").exists():
        package_manager = "pnpm"
    elif (root / "yarn.lock").exists():
        package_manager = "yarn"
    elif not (root / "package-lock.json").exists():
        package_manager = "unknown"
    nextjs = "next" in dependency_names or any(root.glob("next.config.*"))
    vite = "vite" in dependency_names or any(root.glob("vite.config.*"))
    return {
        "root": root,
        "source_set": source_set,
        "packages": packages,
        "entry_files": entry_files,
        "path_mappings": path_mappings,
        "base_urls": base_urls or [root],
        "ecosystem": {
            "detected": bool(packages or any(path.suffix in JS_EXTENSIONS for path in source_set)),
            "package_manager": package_manager,
            "workspaces": has_workspaces,
            "monorepo": has_workspaces or len(packages) > 1 or bool(project_references),
            "package_manifests": [path["path"].relative_to(root).as_posix() for path in packages],
            "tsconfig_paths": sorted(path_mappings),
            "project_references": sorted(project_references),
            "nextjs": nextjs,
            "vite": vite,
        },
    }


def convention_role(path: Path, root: Path, text: str, context: dict[str, Any]) -> str | None:
    relative = path.relative_to(root)
    parts = {part.lower() for part in relative.parts[:-1]}
    name = path.name.lower()
    if path.resolve() in context["entry_files"] or name in ROOT_NAMES:
        return "entry-point"
    if any(part in CONVENTION_DIRECTORIES for part in parts):
        return "config-or-runtime-convention"
    if context["ecosystem"]["nextjs"]:
        if "pages" in parts or ("app" in parts and name in {
            "page.ts", "page.tsx", "layout.ts", "layout.tsx", "route.ts", "route.js",
            "loading.tsx", "error.tsx", "default.tsx", "not-found.tsx",
        }):
            return "nextjs-route"
    if name.startswith(("next.config.", "vite.config.", "webpack.config.", "rollup.config.")):
        return "tool-config"
    if name.startswith("test_") or ".test." in name or ".spec." in name:
        return "test-discovery"
    if any(marker in text[:600].lower() for marker in GENERATED_MARKERS):
        return "generated"
    return None


def collect_knip(root: Path, executable: Path, timeout: int) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    argv = [str(executable), "--reporter", "json", "--no-progress"]
    result = run_approved_tool(argv, root, timeout)
    signals: list[dict[str, Any]] = []
    try:
        payload = json.loads(result.get("stdout") or "{}")
    except json.JSONDecodeError:
        payload = {}
    for issue in payload.get("issues", []):
        issue_file = str(issue.get("file") or "package.json").replace("\\", "/")
        for entry in issue.get("files") or []:
            path = str(entry.get("name") or issue_file).replace("\\", "/")
            signals.append({
                "category": "orphan-file",
                "affected": {"kind": "file", "path": path},
                "evidence": {"family": "knip", "source": "knip.files", "signal": "no-usage-evidence", "detail": "Knip reported the file in its files issue set."},
            })
        for key in ("exports", "types", "nsExports", "nsTypes"):
            for entry in issue.get(key) or []:
                signals.append({
                    "category": "export-no-usage-evidence",
                    "affected": {"kind": "symbol", "path": issue_file, "symbol": str(entry.get("name") or "<unknown>"), "line": entry.get("line")},
                    "evidence": {"family": "knip", "source": f"knip.{key}", "signal": "no-usage-evidence", "detail": f"Knip reported this symbol in its {key} issue set."},
                })
        for key in ("dependencies", "devDependencies", "optionalPeerDependencies"):
            for entry in issue.get(key) or []:
                name = entry.get("name") if isinstance(entry, dict) else entry
                if name:
                    signals.append({
                        "category": "dependency-no-usage-evidence",
                        "affected": {"kind": "dependency", "path": issue_file, "dependency": str(name)},
                        "evidence": {"family": "knip", "source": f"knip.{key}", "signal": "no-usage-evidence", "detail": f"Knip reported this package in its {key} issue set."},
                    })
    tool_run = {
        "tool": "knip",
        "command": result.get("command", " ".join(argv)),
        "execution_mode": result.get("execution_mode", "argv-no-shell"),
        "environment_policy": result.get("environment_policy", {"name": "sanitized-allowlist-v1"}),
        "exit_code": result.get("exit_code"),
        "timed_out": result.get("timed_out", False),
        "redacted": result.get("redacted", False),
        "status": "completed" if result.get("completed", True) else "failed",
        "limitations": ["Knip configuration can contain executable JavaScript or TypeScript and therefore requires prior approval."],
    }
    return signals, tool_run
